### ISSUE TITLE
👏

### ISSUE THREAD

**Issue by nikitapilgrim** [Yiin/ragemp#1]
Thanks for a very good example. There is a question, is it possible to implement hmr frontend in the game? Or maybe there are some options for rapid development?
Ideally, I need to test without reloading game.
I will be very grateful for the answer.

**Comment by Yiin** [comment]
Good question, currently I design my interfaces in a browser (`npm run web`), but given how hot-reloading works, it should be possible to achieve that same functionality in the game. That would require bit different webpack configuration though. I might play with the idea sometime in the future :) If you manage to setup hot reloading before I do, please share! :)

**Comment by nikitapilgrim** [comment]
Well, if I find a solution, I will definitely share it. Thanks again for a great example. I will follow you :)

**Comment by nikitapilgrim** [comment]
https://rage.mp/forums/topic/1306-how-to-enable-cef-debugging/
what you think about this?

**Comment by Yiin** [comment]
yeah CEF debugging is available in the game (it's also possible to use the *Click to inspect* feature in the game itself). I think all we need to do is configure hot-loader to output chunk files to the client_packages folder, and load them from there. I'll try it myself tomorrow.

**Comment by Yiin** [comment]
yeah CEF debugging is available in the game (it's also possible to use the *Click to inspect* feature in the game itself). I think all we need to do is configure hot-loader to output chunk files to the client_packages folder, and load them from there. I'll try it myself tomorrow.
